"""
This module defines the URL patterns for the Routing API.
"""


from typing import List, Union

from django.urls import URLPattern, URLResolver
from rest_framework.routers import DefaultRouter

from shatoru_backend.apps.routing.api.views import StopViewSet

router = DefaultRouter()
router.register("", StopViewSet)

# Define urlpatterns as a list of URL patterns and resolvers for the app's APIs.
# Here, we only have one API endpoint registered with the router, but we can add more
# as needed.
urlpatterns: List[Union[URLPattern, URLResolver]] = [
    # Other APIs here
]

# Add the URLs for the registered API endpoints to urlpatterns.
# Note that these URLs are automatically generated by the router.
urlpatterns += router.urls
